[package]
name = "http3support"
version = "0.1.0"
authors = ["Asur <asur@asurbernardo.com>"]
edition = "2018"

[dependencies]
rocket = { version = "^0.4.2", features = ["tls"] }
rocket_contrib = "*"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
url = "^2.1"