name: Deploy app
on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Pull source
      uses: actions/checkout@master

    - name: Build docker image
      run: 
        docker build . --build-arg key="${{ secrets.PRIVATE_KEY }}" --build-arg cert="${{ secrets.ORIGIN_CERT }}" 
        -t grc.io/http3support/http3support:latest .

    - name: GCP Authenticate
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

    - name: Push docker image
      run: 
         docker push grc.io/http3support/http3support:latest

    - name: GCP List Clusters
      uses: actions/gcloud/cli@master
      with:
        args: run deploy http3support --image grc.io/http3support/http3support:latest